#!/usr/bin/env node
const prompts = require('prompts');
const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '.env');

const BANNER = `
   ╦┬ ┬┌┐┌┬┌─┐┌─┐┬─┐  ╔═╗┌─┐┌┬┐┌┬┐┌─┐┬─┐┌─┐┌─┐
   ║│ │││││├─┘├┤ ├┬┘  ║  │ │││││││├┤ ├┬┘│  ├┤
  ╚╝└─┘┘└┘┴┴  └─┘┴└─  ╚═╝└─┘┴ ┴┴ ┴└─┘┴└─└─┘└─┘
  onX Reference Implementation — Setup
`;

async function main() {
  console.log(BANNER);

  if (fs.existsSync(ENV_PATH)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: '.env already exists. Overwrite?',
      initial: false,
    });
    if (!overwrite) {
      console.log('\n  Keeping existing .env. Exiting.\n');
      process.exit(0);
    }
  }

  const { mode } = await prompts({
    type: 'select',
    name: 'mode',
    message: 'What mode do you want to run?',
    choices: [
      { title: 'Quick Demo', description: 'In-memory data, rate-limited AI, no setup needed', value: 'demo' },
      { title: 'Full Install', description: 'Persistent data, your AI key, settings screen', value: 'full' },
    ],
  });

  if (!mode) process.exit(1);

  const profiles = [];
  const env = {
    APP_MODE: mode,
    DATA_MODE: 'memory',
    DATABASE_URL: '',
    ANTHROPIC_API_KEY: '',
    OPENAI_API_KEY: '',
    GOOGLE_AI_API_KEY: '',
    OLLAMA_URL: '',
    OLLAMA_MODEL: '',
    ONX_MCP_SERVER_URL: '',
    SEED_DATA: 'false',
    SESSION_TTL_MINUTES: '30',
    MAX_MESSAGES_PER_SESSION: '20',
    PORT: '3000',
    NODE_ENV: 'production',
  };

  if (mode === 'demo') {
    env.DATA_MODE = 'memory';
    env.SEED_DATA = 'true';
  } else {
    const { dataStore } = await prompts({
      type: 'select',
      name: 'dataStore',
      message: 'Data store?',
      choices: [
        { title: 'PostgreSQL', description: 'Recommended — runs in Docker, persistent', value: 'postgres' },
        { title: 'SQLite', description: 'Lightweight — single file, no extra container', value: 'sqlite' },
      ],
    });
    if (!dataStore) process.exit(1);

    env.DATA_MODE = dataStore;
    if (dataStore === 'postgres') {
      env.DATABASE_URL = 'postgres://juniper:juniper@db:5432/juniper';
      profiles.push('postgres');
    } else {
      env.DATABASE_URL = 'file:./db/juniper.db';
    }

    const { aiProvider } = await prompts({
      type: 'select',
      name: 'aiProvider',
      message: 'AI provider for the Playground?',
      choices: [
        { title: 'Anthropic (Claude)', value: 'anthropic' },
        { title: 'OpenAI (GPT-4o / GPT-5)', value: 'openai' },
        { title: 'Google Gemini', value: 'gemini' },
        { title: 'Ollama (local, free)', value: 'ollama' },
        { title: 'Skip AI features', value: 'skip' },
      ],
    });
    if (!aiProvider) process.exit(1);

    if (aiProvider === 'anthropic') {
      const { key } = await prompts({ type: 'password', name: 'key', message: 'Anthropic API key:' });
      env.ANTHROPIC_API_KEY = key || '';
    } else if (aiProvider === 'openai') {
      const { key } = await prompts({ type: 'password', name: 'key', message: 'OpenAI API key:' });
      env.OPENAI_API_KEY = key || '';
    } else if (aiProvider === 'gemini') {
      const { key } = await prompts({ type: 'password', name: 'key', message: 'Google AI API key:' });
      env.GOOGLE_AI_API_KEY = key || '';
    } else if (aiProvider === 'ollama') {
      const { url } = await prompts({ type: 'text', name: 'url', message: 'Ollama URL:', initial: 'http://host.docker.internal:11434' });
      env.OLLAMA_URL = url || 'http://host.docker.internal:11434';
      const { model } = await prompts({ type: 'text', name: 'model', message: 'Ollama model:', initial: 'llama3.1' });
      env.OLLAMA_MODEL = model || 'llama3.1';
    }

    const { includeMcp } = await prompts({
      type: 'confirm',
      name: 'includeMcp',
      message: 'Include MCP reference server?',
      initial: false,
    });

    if (includeMcp) {
      profiles.push('mcp');
      env.ONX_MCP_SERVER_URL = 'http://mcp-server:8080';

      const mcpPath = path.resolve(__dirname, '..', 'mcp-reference-server', 'server');
      if (!fs.existsSync(mcpPath)) {
        console.log(`\n  ⚠  MCP server source not found at ${mcpPath}`);
        console.log('  Clone the mcp-reference-server repo alongside this project:');
        console.log('  git clone https://github.com/commerce-operations-foundation/mcp-reference-server.git\n');
      }
    }

    const { seedData } = await prompts({
      type: 'confirm',
      name: 'seedData',
      message: 'Load sample data? (20 products, 9 orders, 6 customers)',
      initial: true,
    });
    env.SEED_DATA = seedData ? 'true' : 'false';
  }

  const envContent = [
    '# Generated by setup.js',
    `APP_MODE=${env.APP_MODE}`,
    `DATA_MODE=${env.DATA_MODE}`,
    env.DATABASE_URL ? `DATABASE_URL=${env.DATABASE_URL}` : '# DATABASE_URL=',
    '',
    env.ANTHROPIC_API_KEY ? `ANTHROPIC_API_KEY=${env.ANTHROPIC_API_KEY}` : '# ANTHROPIC_API_KEY=',
    env.OPENAI_API_KEY ? `OPENAI_API_KEY=${env.OPENAI_API_KEY}` : '# OPENAI_API_KEY=',
    env.GOOGLE_AI_API_KEY ? `GOOGLE_AI_API_KEY=${env.GOOGLE_AI_API_KEY}` : '# GOOGLE_AI_API_KEY=',
    env.OLLAMA_URL ? `OLLAMA_URL=${env.OLLAMA_URL}` : '# OLLAMA_URL=',
    env.OLLAMA_MODEL ? `OLLAMA_MODEL=${env.OLLAMA_MODEL}` : '# OLLAMA_MODEL=',
    '',
    env.ONX_MCP_SERVER_URL ? `ONX_MCP_SERVER_URL=${env.ONX_MCP_SERVER_URL}` : '# ONX_MCP_SERVER_URL=',
    `SEED_DATA=${env.SEED_DATA}`,
    `SESSION_TTL_MINUTES=${env.SESSION_TTL_MINUTES}`,
    `MAX_MESSAGES_PER_SESSION=${env.MAX_MESSAGES_PER_SESSION}`,
    `PORT=${env.PORT}`,
    `NODE_ENV=${env.NODE_ENV}`,
    '',
  ].join('\n');

  fs.writeFileSync(ENV_PATH, envContent);
  console.log('\n  .env written successfully.\n');

  const profileFlags = profiles.map(p => `--profile ${p}`).join(' ');
  const composeCmd = profiles.length > 0
    ? `docker compose ${profileFlags} up --build`
    : 'docker compose up --build';

  console.log('  Run this command to start:\n');
  console.log(`    ${composeCmd}\n`);
  console.log('  Then visit:');
  console.log('    App:      http://localhost:3000');
  console.log('    API docs: http://localhost:3000/api/docs');
  console.log('    OpenAPI:  http://localhost:3000/openapi.yaml');
  console.log('');
}

main().catch(console.error);
