#!/usr/bin/env node
/**
 * Generates db/seed.sql from the TypeScript seed data.
 * Run: node db/generate-seed.js > db/seed.sql
 * 
 * This is a build tool — not shipped to users.
 */
const fs = require('fs');
const path = require('path');

const tenantId = 'juniper_001';
const refDate = new Date('2026-03-15T12:00:00.000Z');
const daysAgo = (n) => new Date(refDate.getTime() - n * 86400000).toISOString();
const daysFromNow = (n) => new Date(refDate.getTime() + n * 86400000).toISOString();

function esc(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
}
function jsonEsc(v) {
  if (v === null || v === undefined) return 'NULL';
  return esc(JSON.stringify(v));
}

const lines = [];
function w(s) { lines.push(s); }

w('-- Juniper Commerce — Seed Data');
w('-- Auto-generated by db/generate-seed.js');
w('-- Idempotent: uses INSERT ... ON CONFLICT DO NOTHING');
w('');
w('BEGIN;');
w('');

// ─── Products ────────────────────────────────────────────────
const products = [
  { id: 'prod_trail_runner', extId: 'ext_trail_runner', created: 180, updated: 10, name: 'Trail Runner Pro', desc: 'High-traction trail running shoe with Vibram Megagrip outsole and waterproof membrane.', handle: 'trail-runner-pro', status: 'active', vendor: 'Juniper', tags: ['footwear','trail','running','waterproof','new-arrival'], cats: ['Footwear'], options: [{name:'Size',values:['8','9','10','11','12']}], images: ['https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Vibram Megagrip outsole, waterproof upper'},{name:'weight',value:'10.2 oz'}] },
  { id: 'prod_approach_shoe', extId: 'ext_approach_shoe', created: 160, updated: 8, name: 'Approach Shoe', desc: 'Precision climbing approach shoe for the scrambling zone.', handle: 'approach-shoe', status: 'active', vendor: 'Juniper', tags: ['footwear','approach','climbing','scrambling'], cats: ['Footwear'], options: [{name:'Size',values:['8','9','10','11','12']}], images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Stealth C4 rubber'},{name:'weight',value:'11.4 oz'}] },
  { id: 'prod_waterproof_boot', extId: 'ext_waterproof_boot', created: 140, updated: 6, name: 'Waterproof Boot', desc: 'Full-grain leather mid boot with Gore-Tex lining.', handle: 'waterproof-boot', status: 'active', vendor: 'Juniper', tags: ['footwear','boot','waterproof','gore-tex','hiking'], cats: ['Footwear'], options: [{name:'Size',values:['8','9','10','11','12']}], images: ['https://images.unsplash.com/photo-1542219550-37153d387c27?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Full-grain leather, Gore-Tex lining'},{name:'weight',value:'2.1 lbs per pair'}] },
  { id: 'prod_hiking_sandal', extId: 'ext_hiking_sandal', created: 50, updated: 2, name: 'River Hiking Sandal', desc: 'Rugged open-toe sandal for river crossings and summer trails.', handle: 'river-hiking-sandal', status: 'active', vendor: 'Juniper', tags: ['footwear','sandal','water','summer','new-arrival'], cats: ['Footwear'], options: [{name:'Size',values:['8','9','10','11','12']}], images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Quick-dry webbing, EVA midsole'},{name:'weight',value:'12.8 oz'}] },
  { id: 'prod_summit_pack', extId: 'ext_summit_pack', created: 200, updated: 5, name: 'Summit Pack 45L', desc: 'Versatile 45-liter hiking pack with aluminum frame stays.', handle: 'summit-pack-45l', status: 'active', vendor: 'Juniper', tags: ['backpack','hiking','camping','carry'], cats: ['Packs & Bags'], options: [{name:'Color',values:['Alpine Green','Slate Gray']}], images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop'], custom: [{name:'capacity',value:'45L'},{name:'frame',value:'Aluminum stays'}] },
  { id: 'prod_day_pack', extId: 'ext_day_pack', created: 130, updated: 4, name: 'Day Pack 22L', desc: 'Streamlined 22-liter daypack for day hikes and commuting.', handle: 'day-pack-22l', status: 'active', vendor: 'Juniper', tags: ['daypack','hiking','skiing','carry'], cats: ['Packs & Bags'], options: [{name:'Color',values:['Storm Blue','Granite','Sunrise Orange']}], images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'], custom: [{name:'capacity',value:'22L'},{name:'rain_cover',value:'Integrated'}] },
  { id: 'prod_duffel', extId: 'ext_duffel', created: 110, updated: 3, name: 'Duffel 60L', desc: '600D nylon duffel that converts to a 65-liter backpack.', handle: 'duffel-60l', status: 'active', vendor: 'Juniper', tags: ['duffel','travel','base-camp','carry','sale'], cats: ['Packs & Bags'], options: [{name:'Color',values:['Black','Navy','Olive']}], images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'], custom: [{name:'capacity',value:'60L'},{name:'material',value:'600D nylon'}] },
  { id: 'prod_waist_pack', extId: 'ext_waist_pack', created: 90, updated: 2, name: 'Waist Pack', desc: '5-liter running and hiking waist pack.', handle: 'waist-pack', status: 'active', vendor: 'Juniper', tags: ['waist-pack','running','trail','carry'], cats: ['Packs & Bags'], options: [{name:'Color',values:['Black','Teal']}], images: ['https://images.unsplash.com/photo-1585916420730-d7f95e942d43?w=600&h=600&fit=crop&auto=format'], custom: [{name:'capacity',value:'5L'},{name:'weight',value:'6.4 oz'}] },
  { id: 'prod_alpine_shelter', extId: 'ext_alpine_shelter', created: 150, updated: 3, name: 'Alpine Shelter 2P', desc: 'Four-season freestanding two-person tent.', handle: 'alpine-shelter-2p', status: 'active', vendor: 'Juniper', tags: ['tent','camping','4-season','shelter'], cats: ['Shelter'], options: [{name:'Configuration',values:['Standard']}], images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop&auto=format'], custom: [{name:'seasons',value:'4-season'},{name:'packed_weight',value:'4.8 lbs'}] },
  { id: 'prod_basecamp_tent', extId: 'ext_basecamp_tent', created: 100, updated: 2, name: 'Basecamp Tent 4P', desc: 'Expedition basecamp tent rated for four occupants.', handle: 'basecamp-tent-4p', status: 'active', vendor: 'Juniper', tags: ['tent','camping','3-season','basecamp','4-person'], cats: ['Shelter'], options: [{name:'Color',values:['Forest','Sand']}], images: ['https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=600&h=600&fit=crop&auto=format'], custom: [{name:'seasons',value:'3-season'},{name:'floor_area',value:'55 sq ft'}] },
  { id: 'prod_hammock', extId: 'ext_hammock', created: 35, updated: 1, name: 'Ultralight Hammock', desc: 'Ripstop nylon camping hammock rated for 400 lbs.', handle: 'ultralight-hammock', status: 'active', vendor: 'Juniper', tags: ['hammock','camping','ultralight','shelter','new-arrival'], cats: ['Shelter'], options: [{name:'Color',values:['Forest Green','Sky Blue']}], images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=600&fit=crop&auto=format'], custom: [{name:'capacity',value:'400 lbs'},{name:'weight',value:'14 oz'}] },
  { id: 'prod_ridgeline_jacket', extId: 'ext_ridgeline_jacket', created: 120, updated: 7, name: 'Ridgeline Jacket', desc: 'Hardshell mountaineering jacket with 3-layer Gore-Tex Pro.', handle: 'ridgeline-jacket', status: 'active', vendor: 'Juniper', tags: ['jacket','hardshell','gore-tex','mountaineering'], cats: ['Apparel'], options: [{name:'Size',values:['XS','S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=600&fit=crop'], custom: [{name:'material',value:'3-layer Gore-Tex Pro'},{name:'waterproof_rating',value:'28,000mm'}] },
  { id: 'prod_merino_base', extId: 'ext_merino_base', created: 85, updated: 4, name: 'Merino Base Layer', desc: '185 g/m² 100% Merino wool crew-neck top.', handle: 'merino-base-layer', status: 'active', vendor: 'Juniper', tags: ['base-layer','merino','wool','apparel'], cats: ['Apparel'], options: [{name:'Size',values:['XS','S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'100% Merino wool'},{name:'certification',value:'Mulesing-free'}] },
  { id: 'prod_softshell_vest', extId: 'ext_softshell_vest', created: 75, updated: 3, name: 'Softshell Vest', desc: 'Wind-resistant softshell vest with Polartec Power Stretch Pro.', handle: 'softshell-vest', status: 'active', vendor: 'Juniper', tags: ['vest','softshell','apparel','layering','sale'], cats: ['Apparel'], options: [{name:'Size',values:['XS','S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Polartec Power Stretch Pro'},{name:'wind_resistance',value:'Yes'}] },
  { id: 'prod_rain_shell', extId: 'ext_rain_shell', created: 65, updated: 2, name: 'Rain Shell', desc: 'Ultralight 2.5-layer rain jacket at 9.5 oz.', handle: 'rain-shell', status: 'active', vendor: 'Juniper', tags: ['rain-jacket','hardshell','ultralight','waterproof'], cats: ['Apparel'], options: [{name:'Size',values:['XS','S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1545594861-3bef43ff2fc8?w=600&h=600&fit=crop&auto=format'], custom: [{name:'weight',value:'9.5 oz'},{name:'waterproof_rating',value:'10,000mm'}] },
  { id: 'prod_insulated_jacket', extId: 'ext_insulated_jacket', created: 30, updated: 1, name: 'Down Insulated Jacket', desc: '800-fill-power responsibly sourced down jacket.', handle: 'down-insulated-jacket', status: 'active', vendor: 'Juniper', tags: ['jacket','down','insulated','ultralight','apparel','new-arrival'], cats: ['Apparel'], options: [{name:'Size',values:['XS','S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=600&h=600&fit=crop&auto=format'], custom: [{name:'fill_power',value:'800'},{name:'weight',value:'12.5 oz'}] },
  { id: 'prod_hiking_pants', extId: 'ext_hiking_pants', created: 25, updated: 1, name: 'Stretch Hiking Pants', desc: 'Lightweight stretch-woven hiking pants with DWR finish.', handle: 'stretch-hiking-pants', status: 'active', vendor: 'Juniper', tags: ['pants','hiking','convertible','apparel'], cats: ['Apparel'], options: [{name:'Size',values:['S','M','L','XL']}], images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Stretch-woven nylon, DWR finish'},{name:'sun_protection',value:'UPF 50+'}] },
  { id: 'prod_hydration_flask', extId: 'ext_hydration_flask', created: 60, updated: 1, name: 'Hydration Flask 32oz', desc: 'Double-wall vacuum-insulated stainless steel bottle.', handle: 'hydration-flask-32oz', status: 'active', vendor: 'Juniper', tags: ['hydration','bottle','insulated','stainless'], cats: ['Accessories'], options: [{name:'Color',values:['Summit Blue','Forest Green','Ember Red']}], images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&auto=format'], custom: [{name:'capacity',value:'32 oz'},{name:'insulation',value:'Double-wall vacuum'}] },
  { id: 'prod_trekking_poles', extId: 'ext_trekking_poles', created: 55, updated: 2, name: 'Trekking Poles', desc: 'Collapsible carbon-fiber trekking poles with cork grips.', handle: 'trekking-poles', status: 'active', vendor: 'Juniper', tags: ['trekking-poles','hiking','accessories','carbon'], cats: ['Accessories'], options: [{name:'Style',values:['Standard',"Women's Fit"]}], images: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=600&fit=crop&auto=format'], custom: [{name:'material',value:'Carbon fiber shaft, cork grip'},{name:'weight',value:'9.8 oz (pair)'}] },
  { id: 'prod_headlamp', extId: 'ext_headlamp', created: 45, updated: 1, name: 'Headlamp 350', desc: '350-lumen LED headlamp with reactive lighting.', handle: 'headlamp', status: 'active', vendor: 'Juniper', tags: ['headlamp','lighting','camping','accessories'], cats: ['Accessories'], options: [{name:'Color',values:['Black','Teal']}], images: ['https://images.unsplash.com/photo-1525811902-f2342640856e?w=600&h=600&fit=crop&auto=format'], custom: [{name:'lumens',value:'350'},{name:'water_resistance',value:'IPX6'}] },
  { id: 'prod_camp_stove', extId: 'ext_camp_stove', created: 40, updated: 1, name: 'Camp Stove', desc: 'Canister-top backpacking stove with piezo igniter.', handle: 'camp-stove', status: 'active', vendor: 'Juniper', tags: ['stove','cooking','backpacking','accessories'], cats: ['Accessories'], options: [{name:'Bundle',values:['Stove Only','Stove + Fuel Canister']}], images: ['https://images.unsplash.com/photo-1517824806704-9040b037703b?w=600&h=600&fit=crop'], custom: [{name:'boil_time',value:'3.5 min / liter'},{name:'weight',value:'3.4 oz'}] },
  { id: 'prod_first_aid', extId: 'ext_first_aid', created: 20, updated: 1, name: 'Wilderness First Aid Kit', desc: 'Comprehensive backcountry first aid kit with 85 supplies.', handle: 'wilderness-first-aid-kit', status: 'active', vendor: 'Juniper', tags: ['first-aid','safety','camping','accessories'], cats: ['Accessories'], options: [{name:'Size',values:['Day Trip','Expedition']}], images: ['https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=600&h=600&fit=crop&auto=format'], custom: [{name:'items',value:'85 pieces'},{name:'case',value:'Water-resistant nylon'}] },
  { id: 'prod_basecamp_bag', extId: 'ext_basecamp_bag', created: 90, updated: 4, name: 'Basecamp Sleeping Bag', desc: '850-fill-power RDS-certified down sleeping bag.', handle: 'basecamp-sleeping-bag', status: 'active', vendor: 'Juniper', tags: ['sleeping-bag','down','camping','backpacking'], cats: ['Sleep'], options: [{name:'Temperature Rating',values:['15°F','30°F']}], images: ['https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&h=600&fit=crop&auto=format'], custom: [{name:'fill_power',value:'850'},{name:'shell_material',value:'20D ripstop nylon'}] },
  { id: 'prod_sleeping_pad', extId: 'ext_sleeping_pad', created: 15, updated: 1, name: 'Insulated Sleeping Pad', desc: 'Self-inflating insulated sleeping pad with R-value 4.5.', handle: 'insulated-sleeping-pad', status: 'active', vendor: 'Juniper', tags: ['sleeping-pad','camping','insulated','backpacking','new-arrival'], cats: ['Sleep'], options: [{name:'Size',values:['Regular','Long']}], images: ['https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&h=600&fit=crop&auto=format'], custom: [{name:'r_value',value:'4.5'},{name:'weight',value:'16 oz'}] },
];

w('-- Products');
for (const p of products) {
  w(`INSERT INTO products (id, external_id, created_at, updated_at, tenant_id, name, description, handle, status, vendor, tags, categories, options, image_urls, custom_fields) VALUES (${esc(p.id)}, ${esc(p.extId)}, ${esc(daysAgo(p.created))}, ${esc(daysAgo(p.updated))}, ${esc(tenantId)}, ${esc(p.name)}, ${esc(p.desc)}, ${esc(p.handle)}, ${esc(p.status)}, ${esc(p.vendor)}, ${jsonEsc(p.tags)}, ${jsonEsc(p.cats)}, ${jsonEsc(p.options)}, ${jsonEsc(p.images)}, ${jsonEsc(p.custom)}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Variants ────────────────────────────────────────────────
w('');
w('-- Product Variants');

function genSizeVariants(productId, prefix, skuPrefix, sizes, created, updated, price, compareAt, cost, weight, image) {
  return sizes.map((size) => ({
    id: `var_${prefix}_${size}`, productId, extId: `ext_var_${prefix}_${size}`,
    created, updated, sku: `${skuPrefix}-${size.padStart(2, '0')}`,
    title: `${productId.replace('prod_','').replace(/_/g,' ')} - Size ${size}`,
    selectedOptions: [{name:'Size',value:size}], price, currency: 'USD',
    compareAtPrice: compareAt, cost, weight, weightUnit: 'lb', image, taxable: 1, invNotTracked: 0,
  }));
}

function genColorVariants(productId, prefix, skuPrefix, colors, codes, created, updated, price, compareAt, cost, weight, image) {
  return colors.map((color, i) => ({
    id: `var_${prefix}_${color.toLowerCase().replace(/[' ]/g, '_')}`, productId,
    extId: `ext_var_${prefix}_${i}`, created, updated, sku: `${skuPrefix}-${codes[i]}`,
    title: `- ${color}`, selectedOptions: [{name:'Color',value:color}],
    price, currency: 'USD', compareAtPrice: compareAt, cost, weight, weightUnit: 'lb',
    image, taxable: 1, invNotTracked: 0,
  }));
}

const variants = [
  ...genSizeVariants('prod_trail_runner','trail','TRP',['8','9','10','11','12'],180,10,189.95,219.95,89.0,0.65,'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&h=600&fit=crop&auto=format'),
  ...genSizeVariants('prod_approach_shoe','approach','APS',['8','9','10','11','12'],160,8,159.95,184.95,74.0,0.72,'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop&auto=format'),
  ...genSizeVariants('prod_waterproof_boot','boot','WPB',['8','9','10','11','12'],140,6,299.95,349.95,142.0,2.1,'https://images.unsplash.com/photo-1542219550-37153d387c27?w=600&h=600&fit=crop&auto=format'),
  ...genSizeVariants('prod_hiking_sandal','sandal','RHS',['8','9','10','11','12'],50,2,89.95,109.95,38.0,0.8,'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&h=600&fit=crop&auto=format'),
  ...genColorVariants('prod_summit_pack','summit','SP45',['Alpine Green','Slate Gray'],['AG','SG'],200,5,279.95,319.95,130.0,4.2,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop'),
  ...genColorVariants('prod_day_pack','daypack','DP22',['Storm Blue','Granite','Sunrise Orange'],['SB','GR','SO'],130,4,149.95,174.95,68.0,1.9,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'),
  ...genColorVariants('prod_duffel','duffel','DFL',['Black','Navy','Olive'],['BK','NV','OL'],110,3,189.95,219.95,86.0,3.2,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'),
  ...genColorVariants('prod_waist_pack','waist','WP5',['Black','Teal'],['BK','TL'],90,2,59.95,69.95,26.0,0.4,'https://images.unsplash.com/photo-1585916420730-d7f95e942d43?w=600&h=600&fit=crop&auto=format'),
  { id: 'var_alpine_std', productId: 'prod_alpine_shelter', extId: 'ext_var_alpine_std', created: 150, updated: 3, sku: 'AS2P-STD', title: 'Alpine Shelter 2P - Standard', selectedOptions: [{name:'Configuration',value:'Standard'}], price: 649.95, currency: 'USD', compareAtPrice: 729.95, cost: 310.0, weight: 4.8, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 },
  ...genColorVariants('prod_basecamp_tent','bc_tent','BCT4',['Forest','Sand'],['FR','SD'],100,2,499.95,579.95,238.0,7.4,'https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=600&h=600&fit=crop&auto=format'),
  ...genColorVariants('prod_hammock','hammock','ULH',['Forest Green','Sky Blue'],['FG','SB'],35,1,79.95,99.95,34.0,0.88,'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=600&fit=crop&auto=format'),
  // Apparel (all size-based XS-XL)
  ...['XS','S','M','L','XL'].map((size,i) => ({ id: `var_ridgeline_${size.toLowerCase()}`, productId: 'prod_ridgeline_jacket', extId: `ext_var_ridgeline_${i}`, created: 120, updated: 7, sku: `RJ-${size}`, title: `Ridgeline Jacket - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 449.95, currency: 'USD', compareAtPrice: 519.95, cost: 215.0, weight: 1.2, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=600&fit=crop', taxable: 1, invNotTracked: 0 })),
  ...['XS','S','M','L','XL'].map((size,i) => ({ id: `var_merino_${size.toLowerCase()}`, productId: 'prod_merino_base', extId: `ext_var_merino_${i}`, created: 85, updated: 4, sku: `MBL-${size}`, title: `Merino Base Layer - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 109.95, currency: 'USD', compareAtPrice: 129.95, cost: 49.0, weight: 0.55, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...['XS','S','M','L','XL'].map((size,i) => ({ id: `var_vest_${size.toLowerCase()}`, productId: 'prod_softshell_vest', extId: `ext_var_vest_${i}`, created: 75, updated: 3, sku: `SSV-${size}`, title: `Softshell Vest - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 139.95, currency: 'USD', compareAtPrice: 159.95, cost: 62.0, weight: 0.7, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...['XS','S','M','L','XL'].map((size,i) => ({ id: `var_rainshell_${size.toLowerCase()}`, productId: 'prod_rain_shell', extId: `ext_var_rainshell_${i}`, created: 65, updated: 2, sku: `RS-${size}`, title: `Rain Shell - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 219.95, currency: 'USD', compareAtPrice: 249.95, cost: 99.0, weight: 0.6, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1545594861-3bef43ff2fc8?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...['XS','S','M','L','XL'].map((size,i) => ({ id: `var_insulated_${size.toLowerCase()}`, productId: 'prod_insulated_jacket', extId: `ext_var_insulated_${i}`, created: 30, updated: 1, sku: `DIJ-${size}`, title: `Down Insulated Jacket - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 329.95, currency: 'USD', compareAtPrice: 379.95, cost: 155.0, weight: 0.78, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...['S','M','L','XL'].map((size,i) => ({ id: `var_pants_${size.toLowerCase()}`, productId: 'prod_hiking_pants', extId: `ext_var_pants_${i}`, created: 25, updated: 1, sku: `SHP-${size}`, title: `Stretch Hiking Pants - ${size}`, selectedOptions: [{name:'Size',value:size}], price: 119.95, currency: 'USD', compareAtPrice: 139.95, cost: 52.0, weight: 0.65, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...genColorVariants('prod_hydration_flask','flask','HF32',['Summit Blue','Forest Green','Ember Red'],['SB','FG','ER'],60,1,44.95,54.95,18.0,0.85,'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&auto=format'),
  ...[{s:'Standard',c:'STD'},{s:"Women's Fit",c:'WMN'}].map((v,i) => ({ id: `var_poles_${i===0?'std':'wmn'}`, productId: 'prod_trekking_poles', extId: `ext_var_poles_${i}`, created: 55, updated: 2, sku: `TKP-${v.c}`, title: `Trekking Poles - ${v.s}`, selectedOptions: [{name:'Style',value:v.s}], price: 179.95, currency: 'USD', compareAtPrice: 209.95, cost: 82.0, weight: 0.62, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...genColorVariants('prod_headlamp','headlamp','HL350',['Black','Teal'],['BK','TL'],45,1,64.95,74.95,28.0,0.2,'https://images.unsplash.com/photo-1525811902-f2342640856e?w=600&h=600&fit=crop&auto=format'),
  ...[{b:'Stove Only',c:'STD',p:89.95,cp:104.95,co:39.0,w:0.21},{b:'Stove + Fuel Canister',c:'BDL',p:114.95,cp:134.95,co:52.0,w:0.6}].map((v,i) => ({ id: `var_stove_${i===0?'solo':'bundle'}`, productId: 'prod_camp_stove', extId: `ext_var_stove_${i}`, created: 40, updated: 1, sku: `CS-${v.c}`, title: `Camp Stove - ${v.b}`, selectedOptions: [{name:'Bundle',value:v.b}], price: v.p, currency: 'USD', compareAtPrice: v.cp, cost: v.co, weight: v.w, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=600&h=600&fit=crop', taxable: 1, invNotTracked: 0 })),
  ...[{s:'Day Trip',c:'DT',p:49.95,cp:59.95,co:22.0,w:0.5},{s:'Expedition',c:'EX',p:89.95,cp:109.95,co:42.0,w:1.2}].map((v,i) => ({ id: `var_firstaid_${i===0?'day':'exp'}`, productId: 'prod_first_aid', extId: `ext_var_firstaid_${i}`, created: 20, updated: 1, sku: `FAK-${v.c}`, title: `Wilderness First Aid Kit - ${v.s}`, selectedOptions: [{name:'Size',value:v.s}], price: v.p, currency: 'USD', compareAtPrice: v.cp, cost: v.co, weight: v.w, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...[{t:'15°F',c:'15F',p:399.95,cp:459.95,co:190.0},{t:'30°F',c:'30F',p:349.95,cp:399.95,co:165.0}].map((v,i) => ({ id: `var_basecamp_${v.c.toLowerCase()}`, productId: 'prod_basecamp_bag', extId: `ext_var_basecamp_${i}`, created: 90, updated: 4, sku: `BSB-${v.c}`, title: `Basecamp Sleeping Bag - ${v.t}`, selectedOptions: [{name:'Temperature Rating',value:v.t}], price: v.p, currency: 'USD', compareAtPrice: v.cp, cost: v.co, weight: 2.4, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
  ...[{s:'Regular',c:'REG',p:179.95,cp:209.95,co:82.0,w:1.0},{s:'Long',c:'LNG',p:199.95,cp:229.95,co:92.0,w:1.3}].map((v,i) => ({ id: `var_pad_${v.s.toLowerCase()}`, productId: 'prod_sleeping_pad', extId: `ext_var_pad_${i}`, created: 15, updated: 1, sku: `ISP-${v.c}`, title: `Insulated Sleeping Pad - ${v.s}`, selectedOptions: [{name:'Size',value:v.s}], price: v.p, currency: 'USD', compareAtPrice: v.cp, cost: v.co, weight: v.w, weightUnit: 'lb', image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&h=600&fit=crop&auto=format', taxable: 1, invNotTracked: 0 })),
];

for (const v of variants) {
  w(`INSERT INTO product_variants (id, product_id, external_id, created_at, updated_at, tenant_id, sku, title, selected_options, price, currency, compare_at_price, cost, weight_value, weight_unit, image_urls, taxable, inventory_not_tracked) VALUES (${esc(v.id)}, ${esc(v.productId)}, ${esc(v.extId)}, ${esc(daysAgo(v.created))}, ${esc(daysAgo(v.updated))}, ${esc(tenantId)}, ${esc(v.sku)}, ${esc(v.title)}, ${jsonEsc(v.selectedOptions)}, ${v.price}, 'USD', ${v.compareAtPrice}, ${v.cost}, ${v.weight}, ${esc(v.weightUnit)}, ${jsonEsc([v.image])}, ${v.taxable}, ${v.invNotTracked}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Customers ────────────────────────────────────────────────
w('');
w('-- Customers');
const customers = [
  { id: 'cust_alex_chen', created: 400, updated: 5, fn: 'Alex', ln: 'Chen', email: 'alex.chen@example.com', phone: '+1-415-555-0101', type: 'individual', status: 'active', addresses: [{name:'home',address:{firstName:'Alex',lastName:'Chen',address1:'847 Pine Street',address2:'Unit 3C',city:'San Francisco',stateOrProvince:'CA',zipCodeOrPostalCode:'94108',country:'US'}}], custom: [{name:'loyalty_tier',value:'gold'},{name:'total_orders',value:'14'}], tags: ['returning','vip','trail-runner'] },
  { id: 'cust_jordan_rivera', created: 30, updated: 1, fn: 'Jordan', ln: 'Rivera', email: 'jordan.rivera@example.com', phone: '+1-303-555-0202', type: 'individual', status: 'active', addresses: [{name:'home',address:{firstName:'Jordan',lastName:'Rivera',address1:'2204 Larimer Street',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80205',country:'US'}}], custom: [{name:'loyalty_tier',value:'bronze'},{name:'total_orders',value:'1'}], tags: ['new-customer'] },
  { id: 'cust_sam_patel', created: 600, updated: 2, fn: 'Sam', ln: 'Patel', email: 'sam.patel@trailheadgear.com', phone: '+1-720-555-0303', type: 'company', status: 'active', addresses: [{name:'business',address:{firstName:'Sam',lastName:'Patel',company:'Trailhead Gear Co.',address1:'1510 Blake Street',address2:'Suite 200',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80202',country:'US'}}], custom: [{name:'loyalty_tier',value:'platinum'},{name:'total_orders',value:'47'},{name:'account_type',value:'wholesale'}], tags: ['wholesale','b2b','priority'] },
  { id: 'cust_maya_okafor', created: 220, updated: 12, fn: 'Maya', ln: 'Okafor', email: 'maya.okafor@example.com', phone: '+1-206-555-0404', type: 'individual', status: 'active', addresses: [{name:'home',address:{firstName:'Maya',lastName:'Okafor',address1:'3412 Fremont Ave N',city:'Seattle',stateOrProvince:'WA',zipCodeOrPostalCode:'98103',country:'US'}}], custom: [{name:'loyalty_tier',value:'silver'},{name:'total_orders',value:'6'}], tags: ['returning','climber'] },
  { id: 'cust_tom_nakamura', created: 90, updated: 7, fn: 'Tom', ln: 'Nakamura', email: 'tom.nakamura@example.com', phone: '+1-801-555-0505', type: 'individual', status: 'active', addresses: [{name:'home',address:{firstName:'Tom',lastName:'Nakamura',address1:'789 Wasatch Blvd',city:'Salt Lake City',stateOrProvince:'UT',zipCodeOrPostalCode:'84108',country:'US'}}], custom: [{name:'loyalty_tier',value:'bronze'},{name:'total_orders',value:'3'}], tags: ['ski-tourer','returning'] },
  { id: 'cust_high_country_outfitters', created: 730, updated: 15, fn: 'Chris', ln: 'Vandenberg', email: 'orders@highcountryoutfitters.com', phone: '+1-970-555-0606', type: 'company', status: 'active', addresses: [{name:'warehouse',address:{firstName:'Chris',lastName:'Vandenberg',company:'High Country Outfitters',address1:'401 Mountain Ave',address2:'Dock B',city:'Fort Collins',stateOrProvince:'CO',zipCodeOrPostalCode:'80524',country:'US'}}], custom: [{name:'loyalty_tier',value:'platinum'},{name:'total_orders',value:'83'},{name:'account_type',value:'wholesale'},{name:'net_terms',value:'Net-30'}], tags: ['wholesale','b2b','priority','net-terms'] },
];

for (const c of customers) {
  w(`INSERT INTO customers (id, created_at, updated_at, tenant_id, first_name, last_name, email, phone, type, status, addresses, custom_fields, tags) VALUES (${esc(c.id)}, ${esc(daysAgo(c.created))}, ${esc(daysAgo(c.updated))}, ${esc(tenantId)}, ${esc(c.fn)}, ${esc(c.ln)}, ${esc(c.email)}, ${esc(c.phone)}, ${esc(c.type)}, ${esc(c.status)}, ${jsonEsc(c.addresses)}, ${jsonEsc(c.custom)}, ${jsonEsc(c.tags)}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Orders ─────────────────────────────────────────────────
w('');
w('-- Orders');
const orders = [
  { id: 'order_JNP_001', extId: 'JNP-2026-001', created: 30, updated: 28, name: 'JNP-2026-001', status: 'shipped', custId: 'cust_alex_chen', custData: {id:'cust_alex_chen',createdAt:daysAgo(400),updatedAt:daysAgo(5),tenantId,firstName:'Alex',lastName:'Chen',email:'alex.chen@example.com',phone:'+1-415-555-0101'}, lineItems: [{id:'li_001_1',sku:'RJ-M',name:'Ridgeline Jacket - M',quantity:1,unitPrice:449.95,totalPrice:449.95},{id:'li_001_2',sku:'BSB-15F',name:'Basecamp Sleeping Bag - 15°F',quantity:1,unitPrice:399.95,totalPrice:399.95}], shipAddr: {firstName:'Alex',lastName:'Chen',address1:'847 Pine Street',address2:'Unit 3C',city:'San Francisco',stateOrProvince:'CA',zipCodeOrPostalCode:'94108',country:'US'}, currency: 'USD', sub: 849.90, tax: 74.37, ship: 0, total: 924.27, source: 'website', carrier: 'UPS', shipClass: 'Ground', tags: ['vip'], custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_002', extId: 'JNP-2026-002', created: 5, updated: 4, name: 'JNP-2026-002', status: 'processing', custId: 'cust_jordan_rivera', custData: {id:'cust_jordan_rivera',createdAt:daysAgo(30),updatedAt:daysAgo(1),tenantId,firstName:'Jordan',lastName:'Rivera',email:'jordan.rivera@example.com',phone:'+1-303-555-0202'}, lineItems: [{id:'li_002_1',sku:'TRP-10',name:'Trail Runner Pro - Size 10',quantity:1,unitPrice:189.95,totalPrice:189.95},{id:'li_002_2',sku:'HF32-SB',name:'Hydration Flask 32oz - Summit Blue',quantity:2,unitPrice:44.95,totalPrice:89.90}], shipAddr: {firstName:'Jordan',lastName:'Rivera',address1:'2204 Larimer Street',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80205',country:'US'}, currency: 'USD', sub: 279.85, tax: 22.39, ship: 8.99, total: 311.23, source: 'website', carrier: null, shipClass: null, tags: null, custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_003', extId: 'JNP-2026-003', created: 60, updated: 58, name: 'JNP-2026-003', status: 'delivered', custId: 'cust_sam_patel', custData: {id:'cust_sam_patel',createdAt:daysAgo(600),updatedAt:daysAgo(2),tenantId,firstName:'Sam',lastName:'Patel',email:'sam.patel@trailheadgear.com',phone:'+1-720-555-0303'}, lineItems: [{id:'li_003_1',sku:'SP45-AG',name:'Summit Pack 45L - Alpine Green',quantity:5,unitPrice:279.95,totalPrice:1399.75},{id:'li_003_2',sku:'SP45-SG',name:'Summit Pack 45L - Slate Gray',quantity:5,unitPrice:279.95,totalPrice:1399.75},{id:'li_003_3',sku:'HF32-FG',name:'Hydration Flask 32oz - Forest Green',quantity:20,unitPrice:44.95,totalPrice:899.00}], shipAddr: {firstName:'Sam',lastName:'Patel',company:'Trailhead Gear Co.',address1:'1510 Blake Street',address2:'Suite 200',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80202',country:'US'}, currency: 'USD', sub: 3698.50, tax: 0, ship: 0, total: 3698.50, source: 'wholesale', carrier: null, shipClass: null, tags: ['wholesale','b2b'], custom: [{name:'source',value:'wholesale'},{name:'discount_applied',value:'15%'}], payStatus: 'paid' },
  { id: 'order_JNP_004', extId: 'JNP-2026-004', created: 10, updated: 9, name: 'JNP-2026-004', status: 'confirmed', custId: 'cust_alex_chen', custData: {id:'cust_alex_chen',createdAt:daysAgo(400),updatedAt:daysAgo(5),tenantId,firstName:'Alex',lastName:'Chen',email:'alex.chen@example.com'}, lineItems: [{id:'li_004_1',sku:'AS2P-STD',name:'Alpine Shelter 2P - Standard',quantity:1,unitPrice:649.95,totalPrice:649.95}], shipAddr: {firstName:'Alex',lastName:'Chen',address1:'847 Pine Street',address2:'Unit 3C',city:'San Francisco',stateOrProvince:'CA',zipCodeOrPostalCode:'94108',country:'US'}, currency: 'USD', sub: 649.95, tax: 56.87, ship: 15.00, total: 721.82, source: 'website', carrier: null, shipClass: null, tags: ['vip'], custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_005', extId: 'JNP-2026-005', created: 18, updated: 16, name: 'JNP-2026-005', status: 'delivered', custId: 'cust_maya_okafor', custData: {id:'cust_maya_okafor',createdAt:daysAgo(220),updatedAt:daysAgo(12),tenantId,firstName:'Maya',lastName:'Okafor',email:'maya.okafor@example.com',phone:'+1-206-555-0404'}, lineItems: [{id:'li_005_1',sku:'APS-10',name:'Approach Shoe - Size 10',quantity:1,unitPrice:159.95,totalPrice:159.95},{id:'li_005_2',sku:'MBL-M',name:'Merino Base Layer - M',quantity:2,unitPrice:109.95,totalPrice:219.90},{id:'li_005_3',sku:'HL350-BK',name:'Headlamp - Black',quantity:1,unitPrice:64.95,totalPrice:64.95}], shipAddr: {firstName:'Maya',lastName:'Okafor',address1:'3412 Fremont Ave N',city:'Seattle',stateOrProvince:'WA',zipCodeOrPostalCode:'98103',country:'US'}, currency: 'USD', sub: 444.80, tax: 44.04, ship: 0, total: 488.84, source: 'website', carrier: 'USPS', shipClass: 'Priority Mail', tags: null, custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_006', extId: 'JNP-2026-006', created: 3, updated: 2, name: 'JNP-2026-006', status: 'confirmed', custId: 'cust_tom_nakamura', custData: {id:'cust_tom_nakamura',createdAt:daysAgo(90),updatedAt:daysAgo(7),tenantId,firstName:'Tom',lastName:'Nakamura',email:'tom.nakamura@example.com',phone:'+1-801-555-0505'}, lineItems: [{id:'li_006_1',sku:'DP22-GR',name:'Day Pack 22L - Granite',quantity:1,unitPrice:149.95,totalPrice:149.95},{id:'li_006_2',sku:'RS-L',name:'Rain Shell - L',quantity:1,unitPrice:219.95,totalPrice:219.95},{id:'li_006_3',sku:'TKP-STD',name:'Trekking Poles - Standard',quantity:1,unitPrice:179.95,totalPrice:179.95}], shipAddr: {firstName:'Tom',lastName:'Nakamura',address1:'789 Wasatch Blvd',city:'Salt Lake City',stateOrProvince:'UT',zipCodeOrPostalCode:'84108',country:'US'}, currency: 'USD', sub: 549.85, tax: 44.24, ship: 12.99, total: 607.08, source: 'website', carrier: null, shipClass: null, tags: null, custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_007', extId: 'JNP-2026-007', created: 45, updated: 42, name: 'JNP-2026-007', status: 'delivered', custId: 'cust_high_country_outfitters', custData: {id:'cust_high_country_outfitters',createdAt:daysAgo(730),updatedAt:daysAgo(15),tenantId,firstName:'Chris',lastName:'Vandenberg',email:'orders@highcountryoutfitters.com',phone:'+1-970-555-0606'}, lineItems: [{id:'li_007_1',sku:'WPB-09',name:'Waterproof Boot - Size 9',quantity:6,unitPrice:299.95,totalPrice:1799.70},{id:'li_007_2',sku:'WPB-10',name:'Waterproof Boot - Size 10',quantity:8,unitPrice:299.95,totalPrice:2399.60},{id:'li_007_3',sku:'WPB-11',name:'Waterproof Boot - Size 11',quantity:6,unitPrice:299.95,totalPrice:1799.70}], shipAddr: {firstName:'Chris',lastName:'Vandenberg',company:'High Country Outfitters',address1:'401 Mountain Ave',address2:'Dock B',city:'Fort Collins',stateOrProvince:'CO',zipCodeOrPostalCode:'80524',country:'US'}, currency: 'USD', sub: 5999.00, tax: 0, ship: 0, total: 5999.00, source: 'wholesale', carrier: null, shipClass: null, tags: ['wholesale','b2b','net-terms'], custom: [{name:'source',value:'wholesale'},{name:'po_number',value:'HCO-2026-0041'}], payStatus: 'paid' },
  { id: 'order_JNP_008', extId: 'JNP-2026-008', created: 2, updated: 1, name: 'JNP-2026-008', status: 'processing', custId: 'cust_maya_okafor', custData: {id:'cust_maya_okafor',createdAt:daysAgo(220),updatedAt:daysAgo(12),tenantId,firstName:'Maya',lastName:'Okafor',email:'maya.okafor@example.com',phone:'+1-206-555-0404'}, lineItems: [{id:'li_008_1',sku:'BCT4-FR',name:'Basecamp Tent 4P - Forest',quantity:1,unitPrice:499.95,totalPrice:499.95},{id:'li_008_2',sku:'CS-BDL',name:'Camp Stove - Stove + Fuel Canister',quantity:1,unitPrice:114.95,totalPrice:114.95},{id:'li_008_3',sku:'HF32-ER',name:'Hydration Flask 32oz - Ember Red',quantity:2,unitPrice:44.95,totalPrice:89.90}], shipAddr: {firstName:'Maya',lastName:'Okafor',address1:'3412 Fremont Ave N',city:'Seattle',stateOrProvince:'WA',zipCodeOrPostalCode:'98103',country:'US'}, currency: 'USD', sub: 704.80, tax: 69.78, ship: 0, total: 774.58, source: 'website', carrier: null, shipClass: null, tags: null, custom: [{name:'source',value:'website'}], payStatus: 'paid' },
  { id: 'order_JNP_009', extId: 'JNP-2026-009', created: 1, updated: 1, name: 'JNP-2026-009', status: 'confirmed', custId: 'cust_jordan_rivera', custData: {id:'cust_jordan_rivera',createdAt:daysAgo(30),updatedAt:daysAgo(1),tenantId,firstName:'Jordan',lastName:'Rivera',email:'jordan.rivera@example.com',phone:'+1-303-555-0202'}, lineItems: [{id:'li_009_1',sku:'SSV-M',name:'Softshell Vest - M',quantity:1,unitPrice:139.95,totalPrice:139.95},{id:'li_009_2',sku:'WP5-TL',name:'Waist Pack - Teal',quantity:1,unitPrice:59.95,totalPrice:59.95}], shipAddr: {firstName:'Jordan',lastName:'Rivera',address1:'2204 Larimer Street',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80205',country:'US'}, currency: 'USD', sub: 199.90, tax: 16.99, ship: 8.99, total: 225.88, source: 'website', carrier: null, shipClass: null, tags: null, custom: [{name:'source',value:'website'}], payStatus: 'authorized' },
];

for (const o of orders) {
  w(`INSERT INTO orders (id, external_id, created_at, updated_at, tenant_id, name, status, customer_id, customer_data, line_items, billing_address, shipping_address, currency, sub_total_price, order_tax, shipping_price, total_price, order_source, shipping_carrier, shipping_class, tags, custom_fields, payment_status) VALUES (${esc(o.id)}, ${esc(o.extId)}, ${esc(daysAgo(o.created))}, ${esc(daysAgo(o.updated))}, ${esc(tenantId)}, ${esc(o.name)}, ${esc(o.status)}, ${esc(o.custId)}, ${jsonEsc(o.custData)}, ${jsonEsc(o.lineItems)}, ${jsonEsc(o.shipAddr)}, ${jsonEsc(o.shipAddr)}, ${esc(o.currency)}, ${o.sub}, ${o.tax}, ${o.ship}, ${o.total}, ${esc(o.source)}, ${esc(o.carrier)}, ${esc(o.shipClass)}, ${jsonEsc(o.tags)}, ${jsonEsc(o.custom)}, ${esc(o.payStatus)}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Fulfillments ────────────────────────────────────────────
w('');
w('-- Fulfillments');
const fulfillments = [
  { id: 'ful_001', created: 27, updated: 25, orderId: 'order_JNP_001', status: 'shipped', tracking: ['1Z999AA10123456784'], carrier: 'UPS', shipClass: 'Ground', expectedDelivery: daysAgo(22), lineItems: [{sku:'RJ-M',name:'Ridgeline Jacket - M',quantity:1},{sku:'BSB-15F',name:'Basecamp Sleeping Bag - 15°F',quantity:1}], shipAddr: {firstName:'Alex',lastName:'Chen',address1:'847 Pine Street',address2:'Unit 3C',city:'San Francisco',stateOrProvince:'CA',zipCodeOrPostalCode:'94108',country:'US'}, locationId: 'WH001' },
  { id: 'ful_003', created: 57, updated: 55, orderId: 'order_JNP_003', status: 'delivered', tracking: ['1Z999BB10987654321','1Z999CC10111213141'], carrier: 'FedEx', shipClass: 'Express', expectedDelivery: daysAgo(53), lineItems: [{sku:'SP45-AG',name:'Summit Pack 45L - Alpine Green',quantity:5},{sku:'SP45-SG',name:'Summit Pack 45L - Slate Gray',quantity:5},{sku:'HF32-FG',name:'Hydration Flask 32oz - Forest Green',quantity:20}], shipAddr: {firstName:'Sam',lastName:'Patel',company:'Trailhead Gear Co.',address1:'1510 Blake Street',address2:'Suite 200',city:'Denver',stateOrProvince:'CO',zipCodeOrPostalCode:'80202',country:'US'}, locationId: 'WH002' },
  { id: 'ful_005', created: 16, updated: 14, orderId: 'order_JNP_005', status: 'delivered', tracking: ['9400111202552820625968'], carrier: 'USPS', shipClass: 'Priority Mail', expectedDelivery: daysAgo(12), lineItems: [{sku:'APS-10',name:'Approach Shoe - Size 10',quantity:1},{sku:'MBL-M',name:'Merino Base Layer - M',quantity:2},{sku:'HL350-BK',name:'Headlamp - Black',quantity:1}], shipAddr: {firstName:'Maya',lastName:'Okafor',address1:'3412 Fremont Ave N',city:'Seattle',stateOrProvince:'WA',zipCodeOrPostalCode:'98103',country:'US'}, locationId: 'WH003' },
  { id: 'ful_007', created: 43, updated: 41, orderId: 'order_JNP_007', status: 'delivered', tracking: ['794644823917','794644823918'], carrier: 'FedEx', shipClass: 'Ground', expectedDelivery: daysAgo(38), lineItems: [{sku:'WPB-09',name:'Waterproof Boot - Size 9',quantity:6},{sku:'WPB-10',name:'Waterproof Boot - Size 10',quantity:8},{sku:'WPB-11',name:'Waterproof Boot - Size 11',quantity:6}], shipAddr: {firstName:'Chris',lastName:'Vandenberg',company:'High Country Outfitters',address1:'401 Mountain Ave',address2:'Dock B',city:'Fort Collins',stateOrProvince:'CO',zipCodeOrPostalCode:'80524',country:'US'}, locationId: 'WH001' },
];

for (const f of fulfillments) {
  w(`INSERT INTO fulfillments (id, created_at, updated_at, tenant_id, order_id, tracking_numbers, line_items, status, shipping_carrier, shipping_class, shipping_address, expected_delivery_date, location_id) VALUES (${esc(f.id)}, ${esc(daysAgo(f.created))}, ${esc(daysAgo(f.updated))}, ${esc(tenantId)}, ${esc(f.orderId)}, ${jsonEsc(f.tracking)}, ${jsonEsc(f.lineItems)}, ${esc(f.status)}, ${esc(f.carrier)}, ${esc(f.shipClass)}, ${jsonEsc(f.shipAddr)}, ${esc(f.expectedDelivery)}, ${esc(f.locationId)}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Returns ────────────────────────────────────────────────
w('');
w('-- Returns');
const returns = [
  { id: 'ret_001', returnNumber: 'RET-JNP-001', orderId: 'order_JNP_001', created: 20, updated: 18, status: 'completed', outcome: 'refund', returnLineItems: [{orderLineItemId:'li_001_2',sku:'BSB-15F',name:'Basecamp Sleeping Bag - 15°F',quantityReturned:1,returnReason:'wrong_size',unitPrice:399.95,refundAmount:399.95,restockFee:0}], totalQuantity: 1, returnTotal: 399.95, refundAmount: 399.95, restockingFee: 0, refundStatus: 'processed', refundMethod: 'original_payment', completedAt: daysAgo(18) },
  { id: 'ret_002', returnNumber: 'RET-JNP-002', orderId: 'order_JNP_005', created: 10, updated: 8, status: 'in_progress', outcome: 'exchange', returnLineItems: [{orderLineItemId:'li_005_1',sku:'APS-10',name:'Approach Shoe - Size 10',quantityReturned:1,returnReason:'wrong_size',unitPrice:159.95,refundAmount:0,restockFee:0}], totalQuantity: 1, returnTotal: 159.95, refundAmount: 0, restockingFee: 0, refundStatus: 'pending', refundMethod: 'store_credit', completedAt: null },
];

for (const r of returns) {
  w(`INSERT INTO returns (id, return_number, order_id, created_at, updated_at, tenant_id, status, outcome, return_line_items, total_quantity, return_total, refund_amount, restocking_fee, refund_status, refund_method, completed_at) VALUES (${esc(r.id)}, ${esc(r.returnNumber)}, ${esc(r.orderId)}, ${esc(daysAgo(r.created))}, ${esc(daysAgo(r.updated))}, ${esc(tenantId)}, ${esc(r.status)}, ${esc(r.outcome)}, ${jsonEsc(r.returnLineItems)}, ${r.totalQuantity}, ${r.returnTotal}, ${r.refundAmount}, ${r.restockingFee}, ${esc(r.refundStatus)}, ${esc(r.refundMethod)}, ${esc(r.completedAt)}) ON CONFLICT (id) DO NOTHING;`);
}

// ─── Inventory ──────────────────────────────────────────────
w('');
w('-- Inventory');
const skuInventory = {
  'TRP-08': { WH001: {oh:24,u:2}, WH002: {oh:18,u:0}, WH003: {oh:10,u:1} },
  'TRP-09': { WH001: {oh:31,u:1}, WH002: {oh:22,u:2}, WH003: {oh:15,u:0} },
  'TRP-10': { WH001: {oh:45,u:3}, WH002: {oh:38,u:2}, WH003: {oh:20,u:1} },
  'TRP-11': { WH001: {oh:28,u:1}, WH002: {oh:19,u:0}, WH003: {oh:12,u:2} },
  'TRP-12': { WH001: {oh:17,u:0}, WH002: {oh:14,u:1}, WH003: {oh:8,u:0} },
  'APS-08': { WH001: {oh:18,u:1}, WH002: {oh:12,u:0}, WH003: {oh:8,u:0} },
  'APS-09': { WH001: {oh:22,u:0}, WH002: {oh:16,u:1}, WH003: {oh:10,u:0} },
  'APS-10': { WH001: {oh:35,u:2}, WH002: {oh:28,u:1}, WH003: {oh:14,u:0} },
  'APS-11': { WH001: {oh:20,u:0}, WH002: {oh:15,u:0}, WH003: {oh:9,u:1} },
  'APS-12': { WH001: {oh:12,u:1}, WH002: {oh:10,u:0}, WH003: {oh:5,u:0} },
  'WPB-08': { WH001: {oh:14,u:0}, WH002: {oh:10,u:1}, WH003: {oh:6,u:0} },
  'WPB-09': { WH001: {oh:19,u:1}, WH002: {oh:15,u:0}, WH003: {oh:8,u:0} },
  'WPB-10': { WH001: {oh:24,u:2}, WH002: {oh:18,u:1}, WH003: {oh:11,u:0} },
  'WPB-11': { WH001: {oh:17,u:0}, WH002: {oh:13,u:0}, WH003: {oh:7,u:1} },
  'WPB-12': { WH001: {oh:10,u:0}, WH002: {oh:8,u:1}, WH003: {oh:4,u:0} },
  'RHS-08': { WH001: {oh:20,u:1}, WH002: {oh:15,u:0}, WH003: {oh:10,u:0} },
  'RHS-09': { WH001: {oh:25,u:0}, WH002: {oh:18,u:1}, WH003: {oh:12,u:0} },
  'RHS-10': { WH001: {oh:30,u:2}, WH002: {oh:22,u:0}, WH003: {oh:15,u:1} },
  'RHS-11': { WH001: {oh:22,u:0}, WH002: {oh:16,u:1}, WH003: {oh:10,u:0} },
  'RHS-12': { WH001: {oh:14,u:1}, WH002: {oh:10,u:0}, WH003: {oh:6,u:0} },
  'SP45-AG': { WH001: {oh:35,u:5}, WH002: {oh:28,u:0}, WH003: {oh:15,u:2} },
  'SP45-SG': { WH001: {oh:29,u:3}, WH002: {oh:24,u:1}, WH003: {oh:12,u:0} },
  'DP22-SB': { WH001: {oh:40,u:2}, WH002: {oh:30,u:1}, WH003: {oh:18,u:0} },
  'DP22-GR': { WH001: {oh:35,u:1}, WH002: {oh:28,u:0}, WH003: {oh:16,u:1} },
  'DP22-SO': { WH001: {oh:22,u:0}, WH002: {oh:18,u:2}, WH003: {oh:10,u:0} },
  'DFL-BK': { WH001: {oh:28,u:1}, WH002: {oh:22,u:0}, WH003: {oh:12,u:0} },
  'DFL-NV': { WH001: {oh:20,u:0}, WH002: {oh:16,u:1}, WH003: {oh:9,u:0} },
  'DFL-OL': { WH001: {oh:15,u:2}, WH002: {oh:12,u:0}, WH003: {oh:7,u:0} },
  'WP5-BK': { WH001: {oh:55,u:3}, WH002: {oh:40,u:2}, WH003: {oh:25,u:0} },
  'WP5-TL': { WH001: {oh:42,u:1}, WH002: {oh:32,u:0}, WH003: {oh:20,u:1} },
  'AS2P-STD': { WH001: {oh:18,u:1}, WH002: {oh:12,u:0}, WH003: {oh:7,u:1} },
  'BCT4-FR': { WH001: {oh:22,u:1}, WH002: {oh:16,u:0}, WH003: {oh:9,u:0} },
  'BCT4-SD': { WH001: {oh:18,u:0}, WH002: {oh:14,u:1}, WH003: {oh:7,u:0} },
  'ULH-FG': { WH001: {oh:35,u:2}, WH002: {oh:28,u:1}, WH003: {oh:18,u:0} },
  'ULH-SB': { WH001: {oh:28,u:1}, WH002: {oh:22,u:0}, WH003: {oh:14,u:1} },
  'RJ-XS': { WH001: {oh:12,u:0}, WH002: {oh:8,u:1}, WH003: {oh:5,u:0} },
  'RJ-S':  { WH001: {oh:22,u:1}, WH002: {oh:18,u:0}, WH003: {oh:9,u:1} },
  'RJ-M':  { WH001: {oh:35,u:2}, WH002: {oh:28,u:1}, WH003: {oh:16,u:0} },
  'RJ-L':  { WH001: {oh:30,u:1}, WH002: {oh:25,u:2}, WH003: {oh:13,u:1} },
  'RJ-XL': { WH001: {oh:19,u:0}, WH002: {oh:15,u:1}, WH003: {oh:8,u:0} },
  'MBL-XS': { WH001: {oh:20,u:0}, WH002: {oh:15,u:1}, WH003: {oh:8,u:0} },
  'MBL-S':  { WH001: {oh:28,u:1}, WH002: {oh:22,u:0}, WH003: {oh:12,u:0} },
  'MBL-M':  { WH001: {oh:40,u:2}, WH002: {oh:32,u:1}, WH003: {oh:18,u:0} },
  'MBL-L':  { WH001: {oh:35,u:1}, WH002: {oh:28,u:0}, WH003: {oh:15,u:1} },
  'MBL-XL': { WH001: {oh:22,u:0}, WH002: {oh:18,u:1}, WH003: {oh:10,u:0} },
  'SSV-XS': { WH001: {oh:16,u:0}, WH002: {oh:12,u:0}, WH003: {oh:6,u:1} },
  'SSV-S':  { WH001: {oh:24,u:1}, WH002: {oh:18,u:0}, WH003: {oh:10,u:0} },
  'SSV-M':  { WH001: {oh:32,u:2}, WH002: {oh:26,u:1}, WH003: {oh:14,u:0} },
  'SSV-L':  { WH001: {oh:28,u:0}, WH002: {oh:22,u:1}, WH003: {oh:12,u:0} },
  'SSV-XL': { WH001: {oh:18,u:1}, WH002: {oh:14,u:0}, WH003: {oh:8,u:0} },
  'RS-XS': { WH001: {oh:14,u:0}, WH002: {oh:10,u:0}, WH003: {oh:6,u:0} },
  'RS-S':  { WH001: {oh:20,u:1}, WH002: {oh:16,u:0}, WH003: {oh:9,u:0} },
  'RS-M':  { WH001: {oh:30,u:2}, WH002: {oh:24,u:1}, WH003: {oh:13,u:0} },
  'RS-L':  { WH001: {oh:26,u:1}, WH002: {oh:20,u:0}, WH003: {oh:11,u:1} },
  'RS-XL': { WH001: {oh:16,u:0}, WH002: {oh:12,u:1}, WH003: {oh:7,u:0} },
  'DIJ-XS': { WH001: {oh:10,u:0}, WH002: {oh:8,u:0}, WH003: {oh:5,u:0} },
  'DIJ-S':  { WH001: {oh:18,u:1}, WH002: {oh:14,u:0}, WH003: {oh:8,u:0} },
  'DIJ-M':  { WH001: {oh:28,u:2}, WH002: {oh:22,u:1}, WH003: {oh:14,u:0} },
  'DIJ-L':  { WH001: {oh:24,u:1}, WH002: {oh:20,u:0}, WH003: {oh:12,u:1} },
  'DIJ-XL': { WH001: {oh:15,u:0}, WH002: {oh:12,u:1}, WH003: {oh:7,u:0} },
  'SHP-S':  { WH001: {oh:20,u:1}, WH002: {oh:16,u:0}, WH003: {oh:10,u:0} },
  'SHP-M':  { WH001: {oh:30,u:2}, WH002: {oh:24,u:1}, WH003: {oh:15,u:0} },
  'SHP-L':  { WH001: {oh:26,u:1}, WH002: {oh:20,u:0}, WH003: {oh:12,u:1} },
  'SHP-XL': { WH001: {oh:16,u:0}, WH002: {oh:12,u:1}, WH003: {oh:8,u:0} },
  'HF32-SB': { WH001: {oh:80,u:5}, WH002: {oh:65,u:3}, WH003: {oh:40,u:2} },
  'HF32-FG': { WH001: {oh:72,u:4}, WH002: {oh:58,u:2}, WH003: {oh:35,u:1} },
  'HF32-ER': { WH001: {oh:68,u:3}, WH002: {oh:54,u:2}, WH003: {oh:30,u:1} },
  'TKP-STD': { WH001: {oh:30,u:1}, WH002: {oh:24,u:0}, WH003: {oh:14,u:0} },
  'TKP-WMN': { WH001: {oh:24,u:0}, WH002: {oh:18,u:1}, WH003: {oh:10,u:0} },
  'HL350-BK': { WH001: {oh:60,u:3}, WH002: {oh:48,u:2}, WH003: {oh:28,u:1} },
  'HL350-TL': { WH001: {oh:42,u:2}, WH002: {oh:34,u:1}, WH003: {oh:20,u:0} },
  'CS-STD': { WH001: {oh:35,u:1}, WH002: {oh:28,u:0}, WH003: {oh:16,u:0} },
  'CS-BDL': { WH001: {oh:22,u:0}, WH002: {oh:18,u:1}, WH003: {oh:10,u:0} },
  'BSB-15F': { WH001: {oh:25,u:2}, WH002: {oh:20,u:0}, WH003: {oh:11,u:1} },
  'BSB-30F': { WH001: {oh:32,u:1}, WH002: {oh:27,u:2}, WH003: {oh:14,u:0} },
  'FAK-DT': { WH001: {oh:50,u:3}, WH002: {oh:40,u:2}, WH003: {oh:25,u:1} },
  'FAK-EX': { WH001: {oh:30,u:1}, WH002: {oh:24,u:0}, WH003: {oh:15,u:0} },
  'ISP-REG': { WH001: {oh:22,u:1}, WH002: {oh:18,u:0}, WH003: {oh:10,u:0} },
  'ISP-LNG': { WH001: {oh:16,u:0}, WH002: {oh:12,u:1}, WH003: {oh:8,u:0} },
};

for (const [sku, warehouses] of Object.entries(skuInventory)) {
  for (const [locId, s] of Object.entries(warehouses)) {
    const avail = s.oh - s.u;
    w(`INSERT INTO inventory (tenant_id, sku, location_id, on_hand, unavailable, available) VALUES (${esc(tenantId)}, ${esc(sku)}, ${esc(locId)}, ${s.oh}, ${s.u}, ${avail}) ON CONFLICT (sku, location_id) DO NOTHING;`);
  }
}

w('');
w('COMMIT;');

const output = lines.join('\n');
const outPath = path.join(__dirname, 'seed.sql');
fs.writeFileSync(outPath, output);
console.log(`Generated ${outPath} (${lines.length} lines)`);
